from app.models.base import Base
from app.models.catalogue import Competition, CompetitionEdition, ExamWindow, Season, SkillRequirement
from app.models.identity import AuditEvent, MagicLink, RefreshToken, RoleAssignment, Tenant, User
from app.models.messaging import (
    CommunicationOptOut,
    Consent,
    ConsentForm,
    ConsentRequest,
    Message,
    MessageDelivery,
    MessageTemplate,
    OutboxEntry,
    PortalNotification,
)
from app.models.operations import (
    Asset,
    AssetLoan,
    AssetRequest,
    BudgetLine,
    ImportBatch,
    MediaAsset,
    MediaSubject,
    ReportJob,
    WebhookDelivery,
    WebhookSubscription,
)
from app.models.people import Guardian, Student, StudentGuardian
from app.models.skills import Insight, Skill, SkillAward, SkillGoal, StudentFlag
from app.models.squads import (
    Attendance,
    Result,
    ResultParticipant,
    Squad,
    SquadMembership,
    SquadTargetEdition,
    TrainingSession,
)

__all__ = [
    "Asset",
    "AssetLoan",
    "AssetRequest",
    "Attendance",
    "AuditEvent",
    "Base",
    "BudgetLine",
    "CommunicationOptOut",
    "Competition",
    "CompetitionEdition",
    "Consent",
    "ConsentForm",
    "ConsentRequest",
    "ExamWindow",
    "Guardian",
    "ImportBatch",
    "Insight",
    "MagicLink",
    "MediaAsset",
    "MediaSubject",
    "Message",
    "MessageDelivery",
    "MessageTemplate",
    "OutboxEntry",
    "PortalNotification",
    "RefreshToken",
    "ReportJob",
    "Result",
    "ResultParticipant",
    "RoleAssignment",
    "Season",
    "Skill",
    "SkillAward",
    "SkillGoal",
    "SkillRequirement",
    "Squad",
    "SquadMembership",
    "SquadTargetEdition",
    "Student",
    "StudentFlag",
    "StudentGuardian",
    "Tenant",
    "TrainingSession",
    "User",
    "WebhookDelivery",
    "WebhookSubscription",
]
