"""Reports, dashboard and media consent (acceptance criteria 13.1.4 and 13.1.10)."""

import io
import time
import zipfile

from httpx import AsyncClient
from openpyxl import load_workbook
from sqlalchemy import text

from app.db import tenant_session
from tests.conftest import World


async def _generate(client: AsyncClient, world: World, rtype: str, fmt: str, actor: str = "leader", **params) -> dict:  # noqa: ANN003
    r = await client.post(f"/api/v1/reports/{rtype}/generate", json={"format": fmt, "params": params},
                          headers=world[actor].headers)
    assert r.status_code == 202, r.text
    job = (await client.get(f"/api/v1/reports/jobs/{r.json()['id']}", headers=world[actor].headers)).json()
    assert job["status"] == "succeeded", job
    return job


async def _download(client: AsyncClient, url: str) -> bytes:
    path = url.split("/api/v1/", 1)[1]
    r = await client.get(f"/api/v1/{path}")
    assert r.status_code == 200
    return r.content


async def test_leader_dashboard_is_six_numbers_with_denominators(client, world: World) -> None:  # noqa: ANN001
    d = (await client.get("/api/v1/dashboard/leader", headers=world["leader"].headers)).json()
    assert set(d) >= {"participation", "skills_coverage", "spend", "upcoming_events", "flagged_students", "trend"}
    assert d["participation"]["denominator"] is not None
    # Alpha has 4 students on roll: a percentage on that base must be withheld, with the reason.
    assert d["participation"]["withheld"] is True
    assert "minimum of 20" in d["participation"]["withheld_reason"]
    assert d["trend"]["available"] is False and "second season" in d["trend"]["reason"]


async def test_every_report_type_exports_in_every_format(client, world: World) -> None:  # noqa: ANN001
    cases = [
        ("student_profile", {"student_id": str(world.ids["a1"])}),
        ("squad_readiness", {"squad_id": str(world.ids["squad_a"])}),
        ("season_review", {}),
        ("cohort_coverage", {}),
        ("inspection_evidence", {}),
        ("plateau_stretch", {}),
        ("kit_utilisation", {}),
    ]
    from app.models import Season

    async with tenant_session(world.tenant) as s:
        s.add(Season(name="Test season", starts_on=__import__("datetime").date(2026, 8, 15),
                     ends_on=__import__("datetime").date(2027, 7, 15)))
        await s.commit()
    for rtype, params in cases:
        actor = "admin" if rtype == "kit_utilisation" else "leader"
        for fmt in ("pdf", "xlsx", "csv", "html"):
            job = await _generate(client, world, rtype, fmt, actor=actor, **params)
            data = await _download(client, job["download_url"])
            if fmt == "pdf":
                assert data.startswith(b"%PDF")
            elif fmt == "xlsx":
                assert load_workbook(io.BytesIO(data)).sheetnames
            elif fmt == "html":
                assert b"Generated by" in data
            else:
                assert data.decode("utf-8-sig").splitlines()[0]


async def test_pdf_and_html_carry_branding_and_the_generating_user(client, world: World) -> None:  # noqa: ANN001
    job = await _generate(client, world, "season_review", "html")
    html = (await _download(client, job["download_url"])).decode()
    assert "Generated by Lena Leader" in html and "Alpha School" in html
    assert "Withheld figures" in html  # small base: the withheld list must be shown, not dropped


async def test_student_without_media_consent_is_pseudonymised_in_generated_reports(client, world: World) -> None:  # noqa: ANN001
    job = await _generate(client, world, "squad_readiness", "html", squad_id=str(world.ids["squad_a"]))
    html = (await _download(client, job["download_url"])).decode()
    assert "Ali Test" not in html  # a2 has no media consent
    assert "no media consent" in html
    assert "Ava Test" in html  # a1 has consent


async def test_teacher_cannot_generate_whole_school_reports(client, world: World) -> None:  # noqa: ANN001
    for rtype in ("season_review", "cohort_coverage", "inspection_evidence"):
        r = await client.post(f"/api/v1/reports/{rtype}/generate", json={}, headers=world["teacher_a"].headers)
        assert r.status_code == 403


async def test_media_upload_refuses_students_without_consent(client, world: World) -> None:  # noqa: ANN001
    files = {"file": ("photo.jpg", b"\xff\xd8\xff fake jpeg", "image/jpeg")}
    r = await client.post("/api/v1/media", files=files, data={"student_ids": f"{world.ids['a2']}"},
                          headers=world["teacher_a"].headers)
    assert r.status_code == 422 and str(world.ids["a2"]) in r.text
    ok = await client.post("/api/v1/media", files=files, data={"student_ids": f"{world.ids['a1']}",
                                                               "caption": "Pit stop"},
                           headers=world["teacher_a"].headers)
    assert ok.status_code == 201


async def test_media_disappears_everywhere_when_consent_is_withdrawn(client, world: World) -> None:  # noqa: ANN001
    files = {"file": ("photo.jpg", b"\xff\xd8\xff another", "image/jpeg")}
    up = await client.post("/api/v1/media", files=files, data={"student_ids": f"{world.ids['sib']}",
                                                               "caption": "Sam on stage"},
                           headers=world["teacher_a"].headers)
    mid = up.json()["id"]
    listed = {m["id"] for m in (await client.get("/api/v1/media", headers=world["admin"].headers)).json()}
    assert mid in listed
    w = await client.post("/api/v1/portal/consents/withdraw", json={"student_id": str(world.ids["sib"]),
                                                                   "purpose": "media"}, headers=world["parent_a"].headers)
    assert w.status_code == 200
    listed = {m["id"] for m in (await client.get("/api/v1/media", headers=world["admin"].headers)).json()}
    assert mid not in listed
    # Enforced in the data layer: the view itself excludes it, whoever queries.
    async with tenant_session(world.tenant) as s:
        rows = (await s.execute(text("SELECT id FROM media_renderable WHERE id = :i"), {"i": mid})).all()
    assert rows == []
    # Restore for other tests.
    await client.post("/api/v1/portal/consents", json={"student_id": str(world.ids["sib"]), "purpose": "media",
                                                       "decision": "granted"}, headers=world["parent_a"].headers)


async def test_subject_access_export_is_complete_and_fast(client, world: World) -> None:  # noqa: ANN001
    t0 = time.perf_counter()
    r = await client.get(f"/api/v1/students/{world.ids['a1']}/export?reason=Parent%20request%20ref%2042",
                         headers=world["leader"].headers)
    elapsed = time.perf_counter() - t0
    assert r.status_code == 200 and elapsed < 60
    z = zipfile.ZipFile(io.BytesIO(r.content))
    names = set(z.namelist())
    assert {"student.json", "guardians.json", "skill_awards.json", "consents.json", "results.json",
            "messages_received_by_family.json", "access_log.json", "summary.html"} <= names
    assert b"ava.parent@example.com" in z.read("guardians.json")
    audit = (await client.get(f"/api/v1/audit?subject_id={world.ids['a1']}&action=student.subject_access_export",
                              headers=world["leader"].headers)).json()
    assert audit["items"][0]["reason"] == "Parent request ref 42"


async def test_cohort_coverage_lists_absent_groups(client, world: World) -> None:  # noqa: ANN001
    r = await client.get("/api/v1/reports/cohort_coverage/preview", headers=world["leader"].headers)
    body = r.json()
    year = next(s for s in body["sections"] if s["heading"] == "Participation by year group")
    assert year["columns"] == ["Year group", "On roll", "Participating", "Rate"]
    assert body["withheld"], "small groups must be listed as withheld"
