"""Export a ReportBody to print-optimised HTML, PDF (same HTML via WeasyPrint), Excel and CSV.
The PDF carries the school's branding and the generating user's name (spec §6.2)."""

import csv
import io
from datetime import UTC, datetime

from jinja2 import Environment, select_autoescape
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

from app.services.reporting.suppression import ReportBody

_env = Environment(autoescape=select_autoescape(["html"]))

HTML = _env.from_string(
    """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>{{ r.title }}</title>
<style>
  @page { size: A4; margin: 18mm 16mm 20mm; @bottom-left { content: "{{ footer }}"; font-size: 8pt; color: #555; }
          @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 8pt; color: #555; } }
  :root { --brand: {{ brand }}; }
  body { font-family: "DejaVu Sans", "Noto Sans", "Noto Sans Arabic", system-ui, sans-serif; color: #1a1a1a;
         font-size: 10.5pt; line-height: 1.45; max-width: 190mm; margin: 0 auto; }
  header { border-bottom: 3px solid var(--brand); padding-bottom: 8px; margin-bottom: 14px; }
  header .school { color: var(--brand); font-weight: 700; letter-spacing: .02em; }
  h1 { font-size: 18pt; margin: 4px 0; } .sub { color: #555; }
  h2 { font-size: 12.5pt; margin: 18px 0 6px; border-left: 4px solid var(--brand); padding-left: 8px; }
  section.inferred h2 { border-left-style: dashed; }
  .tag { display: inline-block; font-size: 7.5pt; text-transform: uppercase; letter-spacing: .06em;
         border: 1px solid #888; border-radius: 3px; padding: 0 4px; margin-left: 6px; color: #444; }
  section.inferred .tag { border-style: dashed; }
  table { width: 100%; border-collapse: collapse; margin: 6px 0; page-break-inside: auto; }
  th, td { border-bottom: 1px solid #ddd; padding: 4px 6px; text-align: start; vertical-align: top; }
  th { background: #f3f4f6; font-weight: 600; }
  tr { page-break-inside: avoid; }
  .figs { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }
  .fig { border: 1px solid #ddd; border-radius: 6px; padding: 8px; }
  .fig .v { font-size: 13pt; font-weight: 700; } .fig .l { color: #444; font-size: 9pt; }
  .fig.withheld .v { color: #92400e; } .fig.inferred { border-style: dashed; }
  .note { color: #555; font-size: 9pt; }
  .withheld-list { background: #fffbeb; border: 1px solid #f59e0b; border-radius: 6px; padding: 8px 12px; }
  @media print { a { color: inherit; } }
</style></head>
<body>
<header>
  <div class="school">{{ school }}</div>
  <h1>{{ r.title }}</h1>
  {% if r.subtitle %}<div class="sub">{{ r.subtitle }}</div>{% endif %}
</header>
{% for s in r.sections %}
<section class="{{ s.claim_type or 'measured' }}">
  <h2>{{ s.heading }}<span class="tag">{{ 'Inferred' if s.claim_type == 'inferred' else 'Measured' }}</span></h2>
  {% if s.kind == 'figures' %}
  <div class="figs">{% for f in s.figures %}
    <div class="fig {{ 'withheld' if f.withheld }} {{ f.claim_type }}">
      <div class="v">{{ f.display }}</div><div class="l">{{ f.label }}</div>
      {% if f.withheld %}<div class="note">Withheld: {{ f.withheld_reason }}</div>{% endif %}
    </div>{% endfor %}</div>
  {% elif s.kind == 'table' %}
    {% if s.rows %}<table><thead><tr>{% for c in s.columns %}<th>{{ c }}</th>{% endfor %}</tr></thead>
    <tbody>{% for row in s.rows %}<tr>{% for cell in row %}<td>{{ cell }}</td>{% endfor %}</tr>{% endfor %}</tbody></table>
    {% else %}<p class="note">No records.</p>{% endif %}
  {% elif s.kind == 'list' %}<ul>{% for i in s['items'] %}<li>{{ i }}</li>{% endfor %}</ul>
  {% else %}<p>{{ s.text }}</p>{% endif %}
  {% if s.note %}<p class="note">{{ s.note }}</p>{% endif %}
</section>
{% endfor %}
{% if r.withheld %}
<h2>Withheld figures</h2>
<div class="withheld-list"><p class="note">These figures exist but are not published, so that small groups of
students cannot be identified. They are listed so readers know the question was asked.</p>
<ul>{% for w in r.withheld %}<li><strong>{{ w.label }}</strong> — {{ w.reason }}</li>{% endfor %}</ul></div>
{% endif %}
<p class="note">{{ footer }}</p>
</body></html>"""
)


def footer_text(user_name: str, school: str) -> str:
    return f"Generated by {user_name} · {school} · {datetime.now(UTC):%d %b %Y %H:%M} UTC · Confidential"


def to_html(r: ReportBody, *, school: str, brand: str, user_name: str) -> str:
    return HTML.render(r=r.as_dict(), school=school, brand=brand, footer=footer_text(user_name, school))


def to_pdf(r: ReportBody, *, school: str, brand: str, user_name: str) -> bytes:
    from weasyprint import HTML as WP

    return WP(string=to_html(r, school=school, brand=brand, user_name=user_name)).write_pdf()


def _cell(v: object) -> object:
    if isinstance(v, dict) and "display" in v:
        return v["display"]
    return v


def to_xlsx(r: ReportBody, *, school: str, user_name: str) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"
    ws.append([school])
    ws.append([r.title])
    ws.append([footer_text(user_name, school)])
    ws["A1"].font = Font(bold=True, size=13)
    ws.append([])
    for s in r.sections:
        if s["kind"] == "figures":
            ws.append([s["heading"], "", "claim: " + (s.get("claim_type") or "measured")])
            for f in s["figures"]:
                ws.append(
                    [
                        f["label"],
                        f["display"],
                        f["denominator"],
                        f["denominator_label"],
                        f["withheld_reason"] or "",
                        f["claim_type"],
                    ]
                )
            ws.append([])
    used: set[str] = {"Summary"}
    for i, s in enumerate(r.sections):
        if s["kind"] not in ("table", "list"):
            continue
        name = "".join(ch for ch in s["heading"] if ch.isalnum() or ch == " ")[:28] or f"Sheet{i}"
        while name in used:
            name = name[:26] + str(i)
        used.add(name)
        sheet = wb.create_sheet(name)
        sheet.append([s["heading"], f"claim: {s.get('claim_type') or 'measured'}"])
        if s["kind"] == "table":
            sheet.append(s["columns"])
            for c in sheet[2]:
                c.font = Font(bold=True)
                c.fill = PatternFill("solid", fgColor="F3F4F6")
            for row in s["rows"]:
                sheet.append([_cell(v) for v in row])
        else:
            for item in s["items"]:
                sheet.append([item])
        if s.get("note"):
            sheet.append([])
            sheet.append([s["note"]])
    if r.withheld:
        sheet = wb.create_sheet("Withheld")
        sheet.append(["Figure", "Reason withheld"])
        for w in r.withheld:
            sheet.append([w["label"], w["reason"]])
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def to_csv(r: ReportBody, *, school: str, user_name: str) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([r.title])
    w.writerow([footer_text(user_name, school)])
    for s in r.sections:
        w.writerow([])
        w.writerow([s["heading"], s.get("claim_type") or "measured"])
        if s["kind"] == "figures":
            w.writerow(
                [
                    "label",
                    "value",
                    "numerator",
                    "denominator",
                    "denominator_label",
                    "withheld_reason",
                    "claim_type",
                ]
            )
            for f in s["figures"]:
                w.writerow(
                    [
                        f["label"],
                        f["display"],
                        f["numerator"],
                        f["denominator"],
                        f["denominator_label"],
                        f["withheld_reason"] or "",
                        f["claim_type"],
                    ]
                )
        elif s["kind"] == "table":
            w.writerow(s["columns"])
            for row in s["rows"]:
                w.writerow([_cell(v) for v in row])
        elif s["kind"] == "list":
            for item in s["items"]:
                w.writerow([item])
        else:
            w.writerow([s.get("text", "")])
    if r.withheld:
        w.writerow([])
        w.writerow(["Withheld figures", "reason"])
        for x in r.withheld:
            w.writerow([x["label"], x["reason"]])
    return ("﻿" + buf.getvalue()).encode("utf-8")
