"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 15:40:36.743216
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_actor_at', 'audit_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_subject', 'audit_events', ['subject_type', 'subject_id'], unique=False)
    op.create_table('consent_forms',
    sa.Column('purpose', sa.Enum('media', 'travel', 'fee_authorisation', 'communications', 'data_processing', name='consentpurpose', native_enum=False, length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('title_ar', sa.String(length=200), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consent_forms_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_forms')),
    sa.UniqueConstraint('tenant_id', 'purpose', 'version', name=op.f('uq_consent_forms_tenant_id_purpose_version'))
    )
    op.create_index(op.f('ix_consent_forms_tenant_id'), 'consent_forms', ['tenant_id'], unique=False)
    op.create_table('exam_windows',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('year_groups', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_exam_windows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_windows'))
    )
    op.create_index(op.f('ix_exam_windows_tenant_id'), 'exam_windows', ['tenant_id'], unique=False)
    op.create_table('outbox',
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'sms', 'in_app', name='channel', native_enum=False, length=40), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_outbox_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index(op.f('ix_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False)
    op.create_table('seasons',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('budget_envelope', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_seasons_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_index(op.f('ix_seasons_tenant_id'), 'seasons', ['tenant_id'], unique=False)
    op.create_table('skills',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('strand', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_label_en', sa.String(length=300), nullable=False),
    sa.Column('parent_label_ar', sa.String(length=300), nullable=False),
    sa.Column('typical_year_group', sa.SmallInteger(), nullable=True),
    sa.Column('framework_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_skills_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('tenant_id', 'code', name=op.f('uq_skills_tenant_id_code'))
    )
    op.create_index(op.f('ix_skills_domain'), 'skills', ['domain'], unique=False)
    op.create_index(op.f('ix_skills_tenant_id'), 'skills', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('mfa_secret_enc', sa.String(length=512), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id_email'))
    )
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('competitions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('organiser', sa.String(length=200), nullable=True),
    sa.Column('discipline', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.Enum('school', 'inter_school', 'emirate', 'national', 'international', name='tier', native_enum=False, length=40), nullable=False),
    sa.Column('entry_format', sa.Enum('team', 'individual', name='entryformat', native_enum=False, length=40), nullable=False),
    sa.Column('typical_field_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'active', 'archived', name='competitionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('proposed_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_competitions_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], name=op.f('fk_competitions_proposed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_competitions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions'))
    )
    op.create_index(op.f('ix_competitions_tenant_id'), 'competitions', ['tenant_id'], unique=False)
    op.create_table('guardians',
    sa.Column('external_mis_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('email_enc', sa.String(length=1024), nullable=True),
    sa.Column('email_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_enc', sa.String(length=1024), nullable=True),
    sa.Column('whatsapp_enc', sa.String(length=1024), nullable=True),
    sa.Column('preferred_channel', sa.Enum('whatsapp', 'email', 'sms', 'in_app', name='channel', native_enum=False, length=40), nullable=False),
    sa.Column('language', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_guardians_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_guardians_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians')),
    sa.UniqueConstraint('tenant_id', 'external_mis_id', name=op.f('uq_guardians_tenant_id_external_mis_id'))
    )
    op.create_index(op.f('ix_guardians_email_hash'), 'guardians', ['email_hash'], unique=False)
    op.create_index(op.f('ix_guardians_tenant_id'), 'guardians', ['tenant_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('previewed', 'committed', 'failed', 'superseded', name='importstatus', native_enum=False, length=40), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('committed_by_id', sa.UUID(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['committed_by_id'], ['users.id'], name=op.f('fk_import_batches_committed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_batches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_batches_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_table('magic_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_magic_links_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_magic_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_magic_links_token_hash'))
    )
    op.create_index(op.f('ix_magic_links_tenant_id'), 'magic_links', ['tenant_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('message_type', sa.Enum('selection_notice', 'logistics', 'consent_request', 'result_notification', 'progress_report', 'attendance_concern', 'celebration', 'non_selection', 'behaviour_note', 'emergency', name='messagetype', native_enum=False, length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'retired', name='templatestatus', native_enum=False, length=40), nullable=False),
    sa.Column('subject_en', sa.String(length=300), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('subject_ar', sa.String(length=300), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('whatsapp_template_name', sa.String(length=120), nullable=True),
    sa.Column('whatsapp_status', sa.Enum('not_submitted', 'pending', 'approved', 'rejected', name='whatsapptemplatestatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_message_templates_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_message_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_message_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates')),
    sa.UniqueConstraint('tenant_id', 'key', 'version', name=op.f('uq_message_templates_tenant_id_key_version'))
    )
    op.create_index(op.f('ix_message_templates_tenant_id'), 'message_templates', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refresh_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('report_jobs',
    sa.Column('report_type', sa.Enum('student_profile', 'squad_readiness', 'season_review', 'cohort_coverage', 'inspection_evidence', 'plateau_stretch', 'kit_utilisation', name='reporttype', native_enum=False, length=40), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'xlsx', 'csv', 'html', name='exportformat', native_enum=False, length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='jobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_report_jobs_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_report_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_jobs'))
    )
    op.create_index(op.f('ix_report_jobs_tenant_id'), 'report_jobs', ['tenant_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('teacher', 'programme_admin', 'leader', 'parent', 'student', name='role', native_enum=False, length=40), nullable=False),
    sa.Column('scope_type', sa.Enum('school', 'squad', 'guardian', 'student', name='scopetype', native_enum=False, length=40), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('granted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_role_assignments_granted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_role_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('user_id', 'role', 'scope_type', 'scope_id', name=op.f('uq_role_assignments_user_id_role_scope_type_scope_id'))
    )
    op.create_index(op.f('ix_role_assignments_scope_id'), 'role_assignments', ['scope_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_tenant_id'), 'role_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('squads',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.String(length=40), nullable=True),
    sa.Column('lead_coach_user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ics_token', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['lead_coach_user_id'], ['users.id'], name=op.f('fk_squads_lead_coach_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_squads_season_id_seasons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_squads_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads')),
    sa.UniqueConstraint('ics_token', name=op.f('uq_squads_ics_token'))
    )
    op.create_index(op.f('ix_squads_tenant_id'), 'squads', ['tenant_id'], unique=False)
    op.create_table('students',
    sa.Column('external_mis_id', sa.String(length=64), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=False),
    sa.Column('preferred_name', sa.String(length=120), nullable=True),
    sa.Column('full_name_ar', sa.String(length=240), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('year_group', sa.Integer(), nullable=False),
    sa.Column('house', sa.String(length=60), nullable=True),
    sa.Column('enrolment_status', sa.Enum('active', 'left', name='enrolmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mis_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_students_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('tenant_id', 'external_mis_id', name=op.f('uq_students_tenant_id_external_mis_id'))
    )
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_students_year_group'), 'students', ['year_group'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secret_enc', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_webhook_subscriptions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhook_subscriptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_subscriptions'))
    )
    op.create_index(op.f('ix_webhook_subscriptions_tenant_id'), 'webhook_subscriptions', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'needs_repair', 'lost', 'retired', name='assetcondition', native_enum=False, length=40), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('assigned_squad_id', sa.UUID(), nullable=True),
    sa.Column('assigned_student_id', sa.UUID(), nullable=True),
    sa.Column('purchased_on', sa.Date(), nullable=True),
    sa.Column('service_due_on', sa.Date(), nullable=True),
    sa.Column('calibration_due_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_squad_id'], ['squads.id'], name=op.f('fk_assets_assigned_squad_id_squads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_student_id'], ['students.id'], name=op.f('fk_assets_assigned_student_id_students'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('tenant_id', 'tag', name=op.f('uq_assets_tenant_id_tag'))
    )
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('communication_opt_outs',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('selection_notice', 'logistics', 'consent_request', 'result_notification', 'progress_report', 'attendance_concern', 'celebration', 'non_selection', 'behaviour_note', 'emergency', name='messagetype', native_enum=False, length=40), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opted_back_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_communication_opt_outs_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_communication_opt_outs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_opt_outs'))
    )
    op.create_index(op.f('ix_communication_opt_outs_tenant_id'), 'communication_opt_outs', ['tenant_id'], unique=False)
    op.create_index('uq_opt_out_active', 'communication_opt_outs', ['guardian_id', 'category'], unique=True, postgresql_where=sa.text('opted_back_in_at IS NULL'))
    op.create_table('competition_editions',
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('tier', sa.Enum('school', 'inter_school', 'emirate', 'national', 'international', name='tier', native_enum=False, length=40), nullable=False),
    sa.Column('registration_opens', sa.Date(), nullable=True),
    sa.Column('registration_closes', sa.Date(), nullable=True),
    sa.Column('event_starts', sa.Date(), nullable=False),
    sa.Column('event_ends', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_field_size', sa.Integer(), nullable=True),
    sa.Column('eligible_year_min', sa.SmallInteger(), nullable=True),
    sa.Column('eligible_year_max', sa.SmallInteger(), nullable=True),
    sa.Column('max_team_size', sa.SmallInteger(), nullable=True),
    sa.Column('external_registration_url', sa.String(length=500), nullable=True),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_editions_competition_id_competitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_competition_editions_season_id_seasons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_competition_editions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_editions'))
    )
    op.create_index(op.f('ix_competition_editions_competition_id'), 'competition_editions', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_editions_tenant_id'), 'competition_editions', ['tenant_id'], unique=False)
    op.create_table('insights',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('rule', sa.String(length=60), nullable=False),
    sa.Column('claim_type', sa.Enum('measured', 'inferred', name='claimtype', native_enum=False, length=40), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_ar', sa.Text(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', name='insightstatus', native_enum=False, length=40), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_text_en', sa.Text(), nullable=True),
    sa.Column('edited_text_ar', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_insights_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_insights_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_insights_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights')),
    sa.UniqueConstraint('student_id', 'period', 'rule', name=op.f('uq_insights_student_id_period_rule'))
    )
    op.create_index(op.f('ix_insights_student_id'), 'insights', ['student_id'], unique=False)
    op.create_index(op.f('ix_insights_tenant_id'), 'insights', ['tenant_id'], unique=False)
    op.create_table('squad_memberships',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('is_reserve', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'withdrawn', name='membershipstatus', native_enum=False, length=40), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('withdrawn_on', sa.Date(), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_memberships_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_squad_memberships_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_squad_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_memberships')),
    sa.UniqueConstraint('squad_id', 'student_id', name=op.f('uq_squad_memberships_squad_id_student_id'))
    )
    op.create_index(op.f('ix_squad_memberships_squad_id'), 'squad_memberships', ['squad_id'], unique=False)
    op.create_index(op.f('ix_squad_memberships_student_id'), 'squad_memberships', ['student_id'], unique=False)
    op.create_index(op.f('ix_squad_memberships_tenant_id'), 'squad_memberships', ['tenant_id'], unique=False)
    op.create_table('student_flags',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('plateau', 'stretch', 'attendance', name='flagkind', native_enum=False, length=40), nullable=False),
    sa.Column('rule', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_student_flags_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_flags_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_student_flags_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_flags'))
    )
    op.create_index(op.f('ix_student_flags_student_id'), 'student_flags', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_flags_tenant_id'), 'student_flags', ['tenant_id'], unique=False)
    op.create_index('uq_student_flags_open', 'student_flags', ['student_id', 'kind'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('student_guardians',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('relationship_label', sa.String(length=40), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('receives_communications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_student_guardians_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_guardians_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_student_guardians_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_guardians')),
    sa.UniqueConstraint('student_id', 'guardian_id', name=op.f('uq_student_guardians_student_id_guardian_id'))
    )
    op.create_index(op.f('ix_student_guardians_guardian_id'), 'student_guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_tenant_id'), 'student_guardians', ['tenant_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('skill_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('client_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_training_sessions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_training_sessions_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_training_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_training_sessions_tenant_id_idempotency_key'))
    )
    op.create_index(op.f('ix_training_sessions_squad_id'), 'training_sessions', ['squad_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_tenant_id'), 'training_sessions', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_response_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], name=op.f('fk_webhook_deliveries_subscription_id_webhook_subscriptions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhook_deliveries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_index(op.f('ix_webhook_deliveries_subscription_id'), 'webhook_deliveries', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_table('asset_loans',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_back_on', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_quantity', sa.Integer(), nullable=True),
    sa.Column('return_condition', sa.Enum('new', 'good', 'fair', 'needs_repair', 'lost', 'retired', name='assetcondition', native_enum=False, length=40), nullable=True),
    sa.Column('issued_by_id', sa.UUID(), nullable=True),
    sa.Column('returned_to_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_loans_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_asset_loans_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_asset_loans_issued_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['returned_to_id'], ['users.id'], name=op.f('fk_asset_loans_returned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_asset_loans_squad_id_squads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_asset_loans_student_id_students'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_asset_loans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_loans'))
    )
    op.create_index(op.f('ix_asset_loans_asset_id'), 'asset_loans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_loans_edition_id'), 'asset_loans', ['edition_id'], unique=False)
    op.create_index(op.f('ix_asset_loans_tenant_id'), 'asset_loans', ['tenant_id'], unique=False)
    op.create_table('asset_requests',
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'approved', 'declined', 'fulfilled', name='assetrequeststatus', native_enum=False, length=40), nullable=False),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_asset_requests_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_asset_requests_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_asset_requests_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_asset_requests_squad_id_squads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_asset_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_requests'))
    )
    op.create_index(op.f('ix_asset_requests_tenant_id'), 'asset_requests', ['tenant_id'], unique=False)
    op.create_table('attendance',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'absent', 'excused', name='attendancestatus', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('client_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_attendance_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_attendance_session_id_training_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('session_id', 'student_id', name=op.f('uq_attendance_session_id_student_id'))
    )
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('entry_fee', 'transport', 'kit', 'cover', 'accommodation', 'other', name='budgetcategory', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=40), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_budget_lines_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_budget_lines_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_budget_lines_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_budget_lines_season_id_seasons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_budget_lines_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_lines'))
    )
    op.create_index(op.f('ix_budget_lines_edition_id'), 'budget_lines', ['edition_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_season_id'), 'budget_lines', ['season_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_tenant_id'), 'budget_lines', ['tenant_id'], unique=False)
    op.create_table('consents',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Enum('media', 'travel', 'fee_authorisation', 'communications', 'data_processing', name='consentpurpose', native_enum=False, length=40), nullable=False),
    sa.Column('consent_form_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.Enum('granted', 'declined', name='consentdecision', native_enum=False, length=40), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['consent_form_id'], ['consent_forms.id'], name=op.f('fk_consents_consent_form_id_consent_forms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_consents_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_consents_guardian_id_guardians'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_consents_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_consents_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index('ix_consents_student_purpose', 'consents', ['student_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('taken_on', sa.Date(), nullable=True),
    sa.Column('is_artefact', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_media_assets_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_media_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_media_assets_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_edition_id'), 'media_assets', ['edition_id'], unique=False)
    op.create_index(op.f('ix_media_assets_tenant_id'), 'media_assets', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_type', sa.Enum('selection_notice', 'logistics', 'consent_request', 'result_notification', 'progress_report', 'attendance_concern', 'celebration', 'non_selection', 'behaviour_note', 'emergency', name='messagetype', native_enum=False, length=40), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'released', 'completed', 'cancelled', 'manual_handoff', name='messagestatus', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('student_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_id', sa.UUID(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('emergency_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_messages_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_messages_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], name=op.f('fk_messages_released_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_messages_squad_id_squads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name=op.f('fk_messages_template_id_message_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_messages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('results',
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('entry_name', sa.String(length=160), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rubric_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('award_title', sa.String(length=200), nullable=True),
    sa.Column('judge_feedback', sa.Text(), nullable=True),
    sa.Column('performance_index', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('data_quality_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('client_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_results_edition_id_competition_editions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_results_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], name=op.f('fk_results_released_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_results_squad_id_squads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_results_tenant_id_idempotency_key'))
    )
    op.create_index(op.f('ix_results_edition_id'), 'results', ['edition_id'], unique=False)
    op.create_index(op.f('ix_results_squad_id'), 'results', ['squad_id'], unique=False)
    op.create_index(op.f('ix_results_tenant_id'), 'results', ['tenant_id'], unique=False)
    op.create_table('skill_goals',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('target_level', sa.SmallInteger(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('origin', sa.Enum('coach', 'gap_suggested', name='goalorigin', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('open', 'achieved', 'dropped', name='goalstatus', native_enum=False, length=40), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_skill_goals_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_skill_goals_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_goals_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_skill_goals_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_skill_goals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_goals'))
    )
    op.create_index(op.f('ix_skill_goals_student_id'), 'skill_goals', ['student_id'], unique=False)
    op.create_index(op.f('ix_skill_goals_tenant_id'), 'skill_goals', ['tenant_id'], unique=False)
    op.create_table('skill_requirements',
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_level', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_skill_requirements_competition_id_competitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_skill_requirements_edition_id_competition_editions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_requirements_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_skill_requirements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_requirements'))
    )
    op.create_index(op.f('ix_skill_requirements_competition_id'), 'skill_requirements', ['competition_id'], unique=False)
    op.create_index(op.f('ix_skill_requirements_edition_id'), 'skill_requirements', ['edition_id'], unique=False)
    op.create_index(op.f('ix_skill_requirements_tenant_id'), 'skill_requirements', ['tenant_id'], unique=False)
    op.create_index('uq_skill_requirements_competition_skill', 'skill_requirements', ['competition_id', 'skill_id'], unique=True, postgresql_where=sa.text('edition_id IS NULL'))
    op.create_index('uq_skill_requirements_edition_skill', 'skill_requirements', ['edition_id', 'skill_id'], unique=True, postgresql_where=sa.text('edition_id IS NOT NULL'))
    op.create_table('squad_target_editions',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_squad_target_editions_edition_id_competition_editions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_target_editions_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_squad_target_editions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_target_editions')),
    sa.UniqueConstraint('squad_id', 'edition_id', name=op.f('uq_squad_target_editions_squad_id_edition_id'))
    )
    op.create_index(op.f('ix_squad_target_editions_edition_id'), 'squad_target_editions', ['edition_id'], unique=False)
    op.create_index(op.f('ix_squad_target_editions_squad_id'), 'squad_target_editions', ['squad_id'], unique=False)
    op.create_index(op.f('ix_squad_target_editions_tenant_id'), 'squad_target_editions', ['tenant_id'], unique=False)
    op.create_table('consent_requests',
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('media', 'travel', 'fee_authorisation', 'communications', 'data_processing', name='consentpurpose', native_enum=False, length=40), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'granted', 'declined', 'expired', name='consentrequeststatus', native_enum=False, length=40), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], name=op.f('fk_consent_requests_consent_id_consents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edition_id'], ['competition_editions.id'], name=op.f('fk_consent_requests_edition_id_competition_editions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_consent_requests_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_consent_requests_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_consent_requests_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consent_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_requests'))
    )
    op.create_index(op.f('ix_consent_requests_guardian_id'), 'consent_requests', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_consent_requests_student_id'), 'consent_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_consent_requests_tenant_id'), 'consent_requests', ['tenant_id'], unique=False)
    op.create_table('media_subjects',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], name=op.f('fk_media_subjects_media_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_media_subjects_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_media_subjects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_subjects')),
    sa.UniqueConstraint('media_id', 'student_id', name=op.f('uq_media_subjects_media_id_student_id'))
    )
    op.create_index(op.f('ix_media_subjects_media_id'), 'media_subjects', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_subjects_student_id'), 'media_subjects', ['student_id'], unique=False)
    op.create_index(op.f('ix_media_subjects_tenant_id'), 'media_subjects', ['tenant_id'], unique=False)
    op.create_table('message_deliveries',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('student_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('language', sa.Enum('en', 'ar', name='language', native_enum=False, length=40), nullable=False),
    sa.Column('channel_planned', sa.Enum('whatsapp', 'email', 'sms', 'in_app', name='channel', native_enum=False, length=40), nullable=False),
    sa.Column('channel_used', sa.Enum('whatsapp', 'email', 'sms', 'in_app', name='channel', native_enum=False, length=40), nullable=True),
    sa.Column('channels_attempted', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'held_quiet_hours', 'throttled', 'blocked_consent', 'blocked_opt_out', 'sent', 'delivered', 'read', 'failed', 'cancelled', name='deliverystatus', native_enum=False, length=40), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('rendered_subject', sa.String(length=400), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('hold_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_message_deliveries_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_deliveries_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_message_deliveries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_deliveries')),
    sa.UniqueConstraint('message_id', 'guardian_id', name=op.f('uq_message_deliveries_message_id_guardian_id')),
    sa.UniqueConstraint('open_token', name=op.f('uq_message_deliveries_open_token'))
    )
    op.create_index('ix_message_deliveries_guardian_sent', 'message_deliveries', ['guardian_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_message_deliveries_message_id'), 'message_deliveries', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_provider_message_id'), 'message_deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_tenant_id'), 'message_deliveries', ['tenant_id'], unique=False)
    op.create_table('result_participants',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['squad_memberships.id'], name=op.f('fk_result_participants_membership_id_squad_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_result_participants_result_id_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_result_participants_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_result_participants_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_participants')),
    sa.UniqueConstraint('result_id', 'student_id', name=op.f('uq_result_participants_result_id_student_id'))
    )
    op.create_index(op.f('ix_result_participants_result_id'), 'result_participants', ['result_id'], unique=False)
    op.create_index(op.f('ix_result_participants_student_id'), 'result_participants', ['student_id'], unique=False)
    op.create_index(op.f('ix_result_participants_tenant_id'), 'result_participants', ['tenant_id'], unique=False)
    op.create_table('skill_awards',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('awarded_on', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('rubric', 'teacher', 'artefact', 'self', name='awardsource', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'verified', 'rejected', 'revoked', name='awardstatus', native_enum=False, length=40), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('artefact_media_id', sa.UUID(), nullable=True),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('rubric_criterion', sa.String(length=80), nullable=True),
    sa.Column('proposed_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('countersigned_by_id', sa.UUID(), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['artefact_media_id'], ['media_assets.id'], name=op.f('fk_skill_awards_artefact_media_id_media_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['countersigned_by_id'], ['users.id'], name=op.f('fk_skill_awards_countersigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], name=op.f('fk_skill_awards_proposed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_skill_awards_result_id_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], name=op.f('fk_skill_awards_revoked_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_skill_awards_session_id_training_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_awards_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_skill_awards_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_skill_awards_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_skill_awards_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_awards')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_skill_awards_tenant_id_idempotency_key'))
    )
    op.create_index('ix_skill_awards_student_skill', 'skill_awards', ['student_id', 'skill_id'], unique=False)
    op.create_index(op.f('ix_skill_awards_tenant_id'), 'skill_awards', ['tenant_id'], unique=False)
    op.create_table('portal_notifications',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), server_default=sa.text("(current_setting('app.tenant_id', true))::uuid"), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['message_deliveries.id'], name=op.f('fk_portal_notifications_delivery_id_message_deliveries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], name=op.f('fk_portal_notifications_guardian_id_guardians'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_portal_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_notifications'))
    )
    op.create_index(op.f('ix_portal_notifications_guardian_id'), 'portal_notifications', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_portal_notifications_tenant_id'), 'portal_notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_notifications_tenant_id'), table_name='portal_notifications')
    op.drop_index(op.f('ix_portal_notifications_guardian_id'), table_name='portal_notifications')
    op.drop_table('portal_notifications')
    op.drop_index(op.f('ix_skill_awards_tenant_id'), table_name='skill_awards')
    op.drop_index('ix_skill_awards_student_skill', table_name='skill_awards')
    op.drop_table('skill_awards')
    op.drop_index(op.f('ix_result_participants_tenant_id'), table_name='result_participants')
    op.drop_index(op.f('ix_result_participants_student_id'), table_name='result_participants')
    op.drop_index(op.f('ix_result_participants_result_id'), table_name='result_participants')
    op.drop_table('result_participants')
    op.drop_index(op.f('ix_message_deliveries_tenant_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_provider_message_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_message_id'), table_name='message_deliveries')
    op.drop_index('ix_message_deliveries_guardian_sent', table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_index(op.f('ix_media_subjects_tenant_id'), table_name='media_subjects')
    op.drop_index(op.f('ix_media_subjects_student_id'), table_name='media_subjects')
    op.drop_index(op.f('ix_media_subjects_media_id'), table_name='media_subjects')
    op.drop_table('media_subjects')
    op.drop_index(op.f('ix_consent_requests_tenant_id'), table_name='consent_requests')
    op.drop_index(op.f('ix_consent_requests_student_id'), table_name='consent_requests')
    op.drop_index(op.f('ix_consent_requests_guardian_id'), table_name='consent_requests')
    op.drop_table('consent_requests')
    op.drop_index(op.f('ix_squad_target_editions_tenant_id'), table_name='squad_target_editions')
    op.drop_index(op.f('ix_squad_target_editions_squad_id'), table_name='squad_target_editions')
    op.drop_index(op.f('ix_squad_target_editions_edition_id'), table_name='squad_target_editions')
    op.drop_table('squad_target_editions')
    op.drop_index('uq_skill_requirements_edition_skill', table_name='skill_requirements', postgresql_where=sa.text('edition_id IS NOT NULL'))
    op.drop_index('uq_skill_requirements_competition_skill', table_name='skill_requirements', postgresql_where=sa.text('edition_id IS NULL'))
    op.drop_index(op.f('ix_skill_requirements_tenant_id'), table_name='skill_requirements')
    op.drop_index(op.f('ix_skill_requirements_edition_id'), table_name='skill_requirements')
    op.drop_index(op.f('ix_skill_requirements_competition_id'), table_name='skill_requirements')
    op.drop_table('skill_requirements')
    op.drop_index(op.f('ix_skill_goals_tenant_id'), table_name='skill_goals')
    op.drop_index(op.f('ix_skill_goals_student_id'), table_name='skill_goals')
    op.drop_table('skill_goals')
    op.drop_index(op.f('ix_results_tenant_id'), table_name='results')
    op.drop_index(op.f('ix_results_squad_id'), table_name='results')
    op.drop_index(op.f('ix_results_edition_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_media_assets_tenant_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_edition_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index('ix_consents_student_purpose', table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_budget_lines_tenant_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_season_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_edition_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_asset_requests_tenant_id'), table_name='asset_requests')
    op.drop_table('asset_requests')
    op.drop_index(op.f('ix_asset_loans_tenant_id'), table_name='asset_loans')
    op.drop_index(op.f('ix_asset_loans_edition_id'), table_name='asset_loans')
    op.drop_index(op.f('ix_asset_loans_asset_id'), table_name='asset_loans')
    op.drop_table('asset_loans')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_subscription_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_training_sessions_tenant_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_squad_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_student_guardians_tenant_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_guardian_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index('uq_student_flags_open', table_name='student_flags', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index(op.f('ix_student_flags_tenant_id'), table_name='student_flags')
    op.drop_index(op.f('ix_student_flags_student_id'), table_name='student_flags')
    op.drop_table('student_flags')
    op.drop_index(op.f('ix_squad_memberships_tenant_id'), table_name='squad_memberships')
    op.drop_index(op.f('ix_squad_memberships_student_id'), table_name='squad_memberships')
    op.drop_index(op.f('ix_squad_memberships_squad_id'), table_name='squad_memberships')
    op.drop_table('squad_memberships')
    op.drop_index(op.f('ix_insights_tenant_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_student_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_competition_editions_tenant_id'), table_name='competition_editions')
    op.drop_index(op.f('ix_competition_editions_competition_id'), table_name='competition_editions')
    op.drop_table('competition_editions')
    op.drop_index('uq_opt_out_active', table_name='communication_opt_outs', postgresql_where=sa.text('opted_back_in_at IS NULL'))
    op.drop_index(op.f('ix_communication_opt_outs_tenant_id'), table_name='communication_opt_outs')
    op.drop_table('communication_opt_outs')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_webhook_subscriptions_tenant_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_students_year_group'), table_name='students')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_squads_tenant_id'), table_name='squads')
    op.drop_table('squads')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_tenant_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_scope_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_report_jobs_tenant_id'), table_name='report_jobs')
    op.drop_table('report_jobs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_message_templates_tenant_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_magic_links_tenant_id'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_guardians_tenant_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_email_hash'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_competitions_tenant_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_tenant_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_domain'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_seasons_tenant_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_outbox_tenant_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_exam_windows_tenant_id'), table_name='exam_windows')
    op.drop_table('exam_windows')
    op.drop_index(op.f('ix_consent_forms_tenant_id'), table_name='consent_forms')
    op.drop_table('consent_forms')
    op.drop_index('ix_audit_subject', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_actor_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('tenants')
    # ### end Alembic commands ###
